apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: dahlia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: dahlia/notification-service:latest
        ports:
        - containerPort: 8085
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: dahlia
spec:
  selector:
    app: notification-service
  ports:
  - port: 8085
    targetPort: 8085
