apiVersion: apps/v1
kind: Deployment
metadata:
  name: export-service
  namespace: sonet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: export-service
  template:
    metadata:
      labels:
        app: export-service
    spec:
      containers:
      - name: export-service
        image: sonet/export-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: export-service
  namespace: sonet
spec:
  selector:
    app: export-service
  ports:
  - port: 8084
    targetPort: 8084
