apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  namespace: dahlia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
      - name: feed-service
        image: dahlia/feed-service:latest
        ports:
        - containerPort: 8084
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: feed-service
  namespace: dahlia
spec:
  selector:
    app: feed-service
  ports:
  - port: 8084
    targetPort: 8084
