apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: dahlia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
      - name: recommendation-service
        image: dahlia/recommendation-service:latest
        ports:
        - containerPort: 9002
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: dahlia
spec:
  selector:
    app: recommendation-service
  ports:
  - port: 9002
    targetPort: 9002
