apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: dahlia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: dahlia/search-service:latest
        ports:
        - containerPort: 9001
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: dahlia
spec:
  selector:
    app: search-service
  ports:
  - port: 9001
    targetPort: 9001
